"""Lower a GraphModule to a self-contained Python module via AOTAutograd + Inductor.

This is the AOT half of the backend contract behind ``torch.precompile``:

    python_code, cache = compile_to_python(gm, example_inputs)

``inductor.compile_to_python`` produces only the inner Inductor ``call`` (kernels
for the post-AOTAutograd dense graph). This module wraps that with the prelude /
epilogue (input-mutation reflection, output-alias regen, subclass wrap/unwrap,
...) by COMPOSING AOTAutograd's own codegen'd runtime-wrapper source -- captured
during compile -- rather than reimplementing it. Each wrapper is re-exec'd with its
own resolved globals (exactly as AOTAutograd does at runtime), so cross-wrapper
references, the inner ``call`` chain, public helpers, and baked metadata objects
(pickle-embedded) are wired without name collisions. The result is a standalone
module exposing ``call(flat_inputs) -> outputs`` that runs on its own
(JIT-compiling kernels); ``cache`` is an opaque acceleration (or None).
"""

from __future__ import annotations

import base64
import pickle
from typing import Any, TYPE_CHECKING

from .subclass_codegen import capture_generated_sources, GeneratedSource


if TYPE_CHECKING:
    from collections.abc import Sequence

    from torch.fx import GraphModule


# Global objects the codegen'd wrappers close over that are reproducible as an
# import in the standalone module (rather than pickle-embedded). Maps object id ->
# (import_statement, expression). Built lazily to avoid import cycles.
def _known_helper_table() -> dict[int, tuple[str, str]]:
    # Generated artifacts import runtime helpers from the single stable surface
    # ``standalone_runtime`` (not scattered AOTAutograd internals).
    import torch

    from . import standalone_runtime as rt

    _RT = "from torch._functorch._aot_autograd.standalone_runtime import"
    table: dict[int, tuple[str, str]] = {
        id(torch): ("import torch", "torch"),
        id(rt.normalize_as_list): (f"{_RT} normalize_as_list", "normalize_as_list"),
        id(torch.autograd.graph.increment_version): (
            "",
            "torch.autograd.graph.increment_version",
        ),
        id(rt.gen_alias_from_base): (
            f"{_RT} gen_alias_from_base",
            "gen_alias_from_base",
        ),
        id(rt._unwrap_tensoralias): (
            f"{_RT} _unwrap_tensoralias",
            "_unwrap_tensoralias",
        ),
        id(rt.CUDARngStateHelper.get_torch_state_as_tuple): (
            f"{_RT} CUDARngStateHelper",
            "CUDARngStateHelper.get_torch_state_as_tuple",
        ),
        id(rt.CUDARngStateHelper.set_new_offset): (
            f"{_RT} CUDARngStateHelper",
            "CUDARngStateHelper.set_new_offset",
        ),
    }
    return table


_MODULE_HEADER = """\
# Generated by torch._functorch.aot_autograd.compile_to_python -- do not edit.
#
# Self-contained, executable module exposing ``call(flat_inputs) -> outputs`` for
# the post-AOTAutograd graph. The Inductor kernels JIT-compile from the inlined
# source on first call (no cache needed). The prelude/epilogue is AOTAutograd's own
# codegen'd runtime wrappers: each is embedded as source and re-exec'd with its
# resolved globals (inner ``call``, sibling wrappers, public helpers, and pickle-
# embedded baked metadata) -- not reimplemented -- so results match eager. The
# companion opaque cache is only an acceleration; this module never reads it.
"""


def _resolve_global(
    obj: Any,
    helper_table: dict[int, tuple[str, str]],
    inner_call_id: int | None,
    fn_id_to_name: dict[int, str],
    imports: set[str],
) -> str:
    """Return a Python expression (valid in the generated module) that reproduces
    ``obj``, recording any needed import. Raises NotImplementedError if ``obj`` is
    neither the inner call, a sibling wrapper, a known helper, nor picklable."""
    if inner_call_id is not None and id(obj) == inner_call_id:
        return "_inner_call"
    if id(obj) in fn_id_to_name:
        return fn_id_to_name[id(obj)]
    if id(obj) in helper_table:
        import_stmt, expr = helper_table[id(obj)]
        if import_stmt:
            imports.add(import_stmt)
        return expr
    # Some orchestration globals are thin forwarding shims around a captured
    # wrapper (e.g. ``_replay_aliases_`` is a bound method that just forwards to the
    # codegen'd ``_alias_fn``). Unwrap a shim that closes over exactly one captured
    # wrapper / the inner call and resolve to it directly.
    import types as _types

    func = obj.__func__ if isinstance(obj, _types.MethodType) else obj
    closure = getattr(func, "__closure__", None)
    if closure:
        refs: list[str] = []
        for cell in closure:
            try:
                val = cell.cell_contents
            except ValueError:
                continue
            if id(val) in fn_id_to_name:
                refs.append(fn_id_to_name[id(val)])
            elif inner_call_id is not None and id(val) == inner_call_id:
                refs.append("_inner_call")
        if len(refs) == 1:
            return refs[0]
    try:
        blob = base64.b64encode(pickle.dumps(obj)).decode("ascii")
    except Exception as e:
        raise NotImplementedError(
            f"aot_autograd.compile_to_python cannot make a runtime-wrapper global "
            f"self-contained: {type(obj).__name__} is not the inner call, a sibling "
            f"wrapper, a known helper, or picklable ({type(e).__name__})."
        ) from e
    return f'_unpickle("{blob}")'


def _compose_standalone_module(
    inner_python: str, captured: list[GeneratedSource]
) -> str:
    """Compose the inner Inductor ``call`` with AOTAutograd's captured runtime
    wrappers into one standalone module exposing ``call(flat_inputs) -> outputs``.

    Each wrapper is embedded as source and re-exec'd with its own globals dict
    (resolved here), then chained: the orchestration is invoked with the
    InductorWrapper chain head as its inner ``compiled_fn``.
    """
    # Backward wrappers are out of scope for forward lowering; reject them up front.
    # Everything else goes through the general engine below and is validated by the
    # correctness self-check in compile_to_python -- including the synthetic-base
    # wrapper (a runtime closure that is never codegen'd, so it cannot appear here;
    # the self-check catches the divergence it causes and raises).
    unsupported = [g.artifact_name for g in captured if "backward" in g.artifact_name]
    if unsupported:
        raise NotImplementedError(
            "aot_autograd.compile_to_python cannot yet compose these runtime "
            f"wrappers into standalone source: {sorted(set(unsupported))}."
        )

    orchestration = [
        g for g in captured if g.artifact_name == "runtime_wrapper_orchestration"
    ]
    if len(orchestration) != 1:
        raise NotImplementedError(
            "aot_autograd.compile_to_python expected exactly one forward "
            f"orchestration wrapper, captured {len(orchestration)}."
        )
    orch = orchestration[0]
    non_orch = [g for g in captured if g is not orch]

    helper_table = _known_helper_table()
    fn_id_to_name = {id(g.fn): f"_wrapper_{i}" for i, g in enumerate(non_orch)}

    # A chain wrapper references the inner it wraps via one of these globals
    # (subclass/dedup use ``compiled_fn``; the functionalized-RNG wrapper uses
    # ``_compiled_fn_``). The orchestration takes its inner as a call-time arg, not a
    # global, so it is never a chain wrapper.
    _INNER_NAMES = ("compiled_fn", "_compiled_fn_")

    def _inner_ref(g: GeneratedSource) -> Any:
        for nm in _INNER_NAMES:
            if nm in g.globals_dict:
                return g.globals_dict[nm]
        return None

    # The inner Inductor call is the inner-reference that is not itself a captured
    # wrapper (the innermost link of the chain). It may be absent (dense / alias
    # graphs have no chain wrapper); then the orchestration is invoked with
    # ``_inner_call`` directly.
    inner_call_id: int | None = None
    for g in captured:
        cf = _inner_ref(g)
        if cf is not None and id(cf) not in fn_id_to_name:
            inner_call_id = id(cf)
            break

    imports: set[str] = set()
    wrapper_blocks: list[str] = []
    for i, g in enumerate(non_orch):
        name = fn_id_to_name[id(g.fn)]
        binds: list[str] = []
        for gname, gobj in g.globals_dict.items():
            if gname == "__builtins__":
                continue
            expr = _resolve_global(
                gobj, helper_table, inner_call_id, fn_id_to_name, imports
            )
            binds.append(f"        {gname!r}: {expr},")
        wrapper_blocks.append(
            f"{name}_src = '''\n{g.source}\n'''\n"
            f"{name} = _exec_wrapper({name}_src, {g.fn_name!r}, {{\n"
            + "\n".join(binds)
            + "\n})\n"
        )

    # Orchestration globals (it takes the inner chain as a call-time arg, not a
    # global, so ``compiled_fn`` is absent here).
    orch_binds: list[str] = []
    for gname, gobj in orch.globals_dict.items():
        if gname == "__builtins__":
            continue
        expr = _resolve_global(
            gobj, helper_table, inner_call_id, fn_id_to_name, imports
        )
        orch_binds.append(f"        {gname!r}: {expr},")

    # Chain head passed to the orchestration: the outermost InductorWrapper (last
    # non-orch wrapper that wraps via an inner reference), else the inner call.
    chain_head = "_inner_call"
    for g in non_orch:
        if _inner_ref(g) is not None:
            chain_head = fn_id_to_name[id(g.fn)]

    parts = [
        _MODULE_HEADER,
        "import base64 as _base64",
        "import contextlib",
        "import pickle as _pickle",
        *sorted(imports),
        "",
        "",
        "def _unpickle(s):",
        "    return _pickle.loads(_base64.b64decode(s))",
        "",
        "",
        "def _exec_wrapper(src, fn_name, glb):",
        "    # Re-exec one AOTAutograd-codegen'd wrapper with its own globals, exactly",
        "    # as AOTAutograd does at runtime -- avoids cross-wrapper name collisions.",
        "    local_ns = {}",
        "    exec(compile(src, '<aot_wrapper>', 'exec'), glb, local_ns)",
        "    return local_ns[fn_name]",
        "",
        "",
        "# " + "=" * 70,
        "# Inner Inductor output code (kernels + ``call``)",
        "# " + "=" * 70,
        inner_python,
        "_inner_call = call",
        "",
        "# " + "=" * 70,
        "# AOTAutograd runtime wrappers (codegen'd; re-exec'd with resolved globals)",
        "# " + "=" * 70,
        *wrapper_blocks,
        f"_orchestration_src = '''\n{orch.source}\n'''",
        f"_orchestration = _exec_wrapper(_orchestration_src, {orch.fn_name!r}, {{",
        *orch_binds,
        "})",
        "",
        "",
        "def call(flat_inputs):  # noqa: F811",
        "    # AOTAutograd orchestration: disables grad, invokes the inner chain,",
        "    # bumps mutated-input versions, applies the output epilogue.",
        "    return _orchestration(",
        f"        {chain_head}, contextlib.nullcontext, lambda: None, list(flat_inputs)",
        "    )",
        "",
    ]
    return "\n".join(parts)


def _flatten_to_dense(t: Any, out: list[Any]) -> None:
    flatten = getattr(t, "__tensor_flatten__", None)
    if flatten is None:
        out.append(t)
        return
    attrs, _ = flatten()
    for a in attrs:
        _flatten_to_dense(getattr(t, a), out)


def _outputs_match(a: Any, b: Any, *, values: bool) -> bool:
    import torch

    a = list(a) if isinstance(a, (list, tuple)) else [a]
    b = list(b) if isinstance(b, (list, tuple)) else [b]
    da: list[Any] = []
    db: list[Any] = []
    for t in a:
        _flatten_to_dense(t, da)
    for t in b:
        _flatten_to_dense(t, db)
    if len(da) != len(db):
        return False
    for x, y in zip(da, db):
        if isinstance(x, torch.Tensor) and isinstance(y, torch.Tensor):
            # ``values=False`` (e.g. functionalized RNG) compares structure only:
            # the two execution paths legitimately draw different random values.
            if x.shape != y.shape or x.dtype != y.dtype:
                return False
            if values and not torch.allclose(
                x, y, atol=1e-3, rtol=1e-3, equal_nan=True
            ):
                return False
        elif x != y:
            return False
    return True


def _verify_composition(
    source: str,
    gm: GraphModule,
    example_inputs: Sequence[Any],
    *,
    values: bool,
) -> None:
    """Run the composed module against the eager graph on the example inputs and
    raise if they diverge. This is the safety net for composition gaps we cannot
    enumerate (e.g. the synthetic-base wrapper is a runtime closure that is never
    codegen'd, so it cannot be captured/composed) -- better to refuse than emit a
    silently-incorrect artifact. ``values=False`` checks structure only, for
    nondeterministic graphs (functionalized RNG)."""
    import torch

    def _cloned_inputs() -> list[Any]:
        # Preserve identity aliasing (the same tensor object passed twice -> one
        # clone) so the self-check exercises that aliasing. NOTE: it does not
        # reconstruct *storage* aliasing across distinct view objects (e.g.
        # base[:3]/base[3:]); a genuine synthetic-base divergence across distinct
        # views is therefore not guaranteed to be caught here. In practice make_fx
        # resolves most such aliasing at trace time, and synthetic-base rarely fires.
        memo: dict[int, Any] = {}
        out: list[Any] = []
        for t in example_inputs:
            if isinstance(t, torch.Tensor):
                out.append(memo.setdefault(id(t), t.detach().clone()))
            else:
                out.append(t)
        return out

    with torch.no_grad():
        ref = gm(_cloned_inputs())
    ns: dict[str, Any] = {"__name__": "_aot_verify"}
    exec(compile(source, "<aot_verify>", "exec"), ns)
    got = ns["call"](_cloned_inputs())
    if not _outputs_match(ref, got, values=values):
        raise NotImplementedError(
            "aot_autograd.compile_to_python: the composed standalone module does not "
            "reproduce the graph (likely an unhandled runtime wrapper, e.g. synthetic "
            "base for storage-aliased mutated inputs). Refusing to emit a "
            "silently-incorrect artifact."
        )


def compile_to_python(
    gm: GraphModule,
    example_inputs: Sequence[Any],
    *,
    dynamic_shapes: str = "from_example_inputs",
    options: Any = None,
) -> tuple[str, bytes | None]:
    """Compile ``gm`` to ``(python_code, cache)``; see the module docstring."""
    from torch._inductor import compile_to_python as _inductor_compile_to_python

    captured: list[GeneratedSource] = []
    with capture_generated_sources(captured):
        inner_python, cache = _inductor_compile_to_python(
            gm,
            example_inputs,
            dynamic_shapes=dynamic_shapes,  # type: ignore[arg-type]
            options=options,
        )
    source = _compose_standalone_module(inner_python, captured)
    # Functionalized RNG draws different random values along the two execution paths,
    # so verify structure only for it; otherwise verify values.
    has_rng = any(g.artifact_name == "functionalized_rng_wrapper" for g in captured)
    _verify_composition(source, gm, example_inputs, values=not has_rng)
    return source, cache
